### PR TITLE
do not allow selection to contain duplicates

### PR DESCRIPTION
**Pull request by PythonFZ**

### CODE REVIEW

**Review by RokasEl — COMMENTED** [review]
Why don't you just filter duplicates in the selection rather than raising a ValueError?

**Comment by PythonFZ** [comment]
> Why don't you just filter duplicates in the selection rather than raising a ValueError?

My motivation was, to let the user know that duplicates will not be possible. When filtering them silently e.g. via `list(set(...))`, they will not notice that something might be wrong.

**Comment by RokasEl** [comment]
Perhaps throw a warning instead? My worry is that something might happen in the webclient to accidentally cause a double selection. We don't want value errors thrown around in that case.

**Comment by PythonFZ** [comment]
> Perhaps throw a warning instead? My worry is that something might happen in the webclient to accidentally cause a double selection. We don't want value errors thrown around in that case.

The webclient uses a set for selection, so it should not be possible to cause any issue there:

https://github.com/zincware/ZnDraw/blob/d61512aa2783040c34de9662ce78f61300dc088d/app/src/App.tsx#L71

**Comment by RokasEl** [comment]
In which case I think this is fine to merge.

**Pull request merged**
