### PR TITLE
Allow manual coloring of atoms

### PR DESCRIPTION
**Pull request by phohenberger**
Allows sending a manual coloring of atoms with the atoms.colors attribute

### CODE REVIEW

**Comment by PythonFZ** [comment]
I like the feature and it works nicely. But I'd suggest some changes:

I'd like to be able to access the colors when retrieving the atoms like:

```python
from zndraw import ZnDraw
vis = ZnDraw(url="http://127.0.0.1:1234/")

print(vis[0].colors) # list
```

I think this also has to be a potential to be expanded by some general information.
Currently, we are limited to particles from the periodic system, but once e.g. coarse grained simulations are of interested, we might want to be able to parse additional informations (probably through `atoms.info`).

My suggestion would be to expand this to generally work with `atoms.info` and use `atoms.info["colors"]: list` instead of `atoms.color`.

```python
from zndraw import ZnDraw
vis = ZnDraw(url="http://127.0.0.1:1234/")

atoms = ase.build.molecule("H2O")
atoms.info["colors"] = [None, "#FF3333", None] # None = fill color automatically
vis[0] = atoms

print(atoms.info["colors"]) # ["#FFFFFF", "#FF3333", "#FFFFFF"] # automatic color for hydrogens is  white.
```

**Review by PythonFZ — CHANGES_REQUESTED** [review]
Looks Good, please consider my comment above.

**Comment by phohenberger** [comment]
This would definitely be a good addition. The info tag could also be used as a means to save information about future features such as vector-fields and obstacles. I will look into it.

**Comment by PythonFZ** [comment]
or better use `atoms.arrays["colors"]`

**Comment by phohenberger** [comment]
Should work as intended now. Individual atoms can be manually colored before handing them to ZnDraw using
`atoms.arrays["colors"] = ["#ffffff", "#000000", etc]`

**Review by PythonFZ — APPROVED** [review]
Looks good!

**Pull request merged**
